name: my_solved
description: For solving problems in the world of programming; base on solved.ac

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.4+73

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  extended_image: ^8.1.0
  fluttertoast: ^8.2.8
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_radar_chart: ^0.2.1
  pie_chart: ^5.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  flutter_widget_from_html_core: ^0.14.11
  html: ^0.15.2
  http: ^1.1.0
  intl: ^0.18.0
  meta: ^1.9.1
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  permission_handler: ^11.3.1

  boj_api:
    path: packages/apis/boj_api
  notification_api:
    path: packages/apis/notification_api
  shared_preferences_api:
    path: packages/apis/shared_preferences_api
  solved_api:
    path: packages/apis/solved_api
  contest_notification_repository:
    path: packages/repositories/contest_notification_repository
  contest_repository:
    path: packages/repositories/contest_repository
  search_repository:
    path: packages/repositories/search_repository
  shared_preferences_repository:
    path: packages/repositories/shared_preferences_repository
  streak_notification_repository:
    path: packages/repositories/streak_notification_repository
  user_repository:
    path: packages/repositories/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/classes/
    - assets/images/tiers/
    - assets/images/icons/
    - assets/images/venues/

fonts:
  - family: SourceCodePro
    fonts:
      - asset: assets/fonts/SourceCodePro-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/SourceCodePro-Light.ttf
        weight: 300
      - asset: assets/fonts/SourceCodePro-Regular.ttf
        weight: 400
      - asset: assets/fonts/SourceCodePro-Medium.ttf
        weight: 500
      - asset: assets/fonts/SourceCodePro-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/SourceCodePro-Bold.ttf
        weight: 700
      - asset: assets/fonts/SourceCodePro-Black.ttf
        weight: 900
  - family: Pretendard
    fonts:
      - asset: assets/fonts/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/fonts/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Pretendard-Light.ttf
        weight: 300
      - asset: assets/fonts/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/fonts/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/fonts/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/fonts/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Pretendard-Black.ttf
        weight: 900
