name: contest_notification_repository
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  notification_api:
    path: ../../apis/notification_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0