name: search_repository
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  solved_api:
    path: ../../apis/solved_api

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4