name: contest_repository
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  boj_api:
    path: ../../apis/boj_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.4