name: boj_api
description: A Dart API Client for the boj api
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.16.4
  flutter_lints: ^2.0.0
