default_platform(:ios)

platform :ios do
  desc "Deploy to App Store directly 🚀"
  lane :release do
    build_app(
      export_method: "app-store"
    )

    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: true,
      automatic_release: true,
    )
  end
end
