name: my_solved
description: For solving problems in the world of programming; base on solved.ac

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+42

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  html: ^0.15.1
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  extended_image: ^6.3.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  flutter_radar_chart: ^0.2.1
  fluttertoast: ^8.2.1
  flutter_native_timezone: ^2.0.0
  #  flutter_local_notifications: ^8.2.0
  #  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/classes/
    - lib/assets/tiers/
    - lib/assets/icons/

fonts:
  - family: SourceCodePro
    fonts:
      - asset: lib/assets/fonts/SourceCodePro-ExtraLight.ttf
        weight: 200
      - asset: lib/assets/fonts/SourceCodePro-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/SourceCodePro-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/SourceCodePro-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/SourceCodePro-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/SourceCodePro-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/SourceCodePro-Black.ttf
        weight: 900
  - family: Pretendard
    fonts:
      - asset: lib/assets/fonts/Pretendard-Thin.ttf
        weight: 100
      - asset: lib/assets/fonts/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: lib/assets/fonts/Pretendard-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Pretendard-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Pretendard-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Pretendard-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Pretendard-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: lib/assets/fonts/Pretendard-Black.ttf
        weight: 900