name: my_solved
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  http: ^0.13.3
  provider: ^6.0.1
  html: ^0.15.1
  flutter_html: ^2.1.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  extended_image: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/classes/
    - lib/assets/tiers/
    - lib/assets/icons/